name: Sync to Heroicons
on:
  schedule:
    - cron: '20 4 * * 0,3,5'
  workflow_dispatch:

jobs:
  Check-Version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          github_token: ${{ secrets.PAT }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          always-auth: true

      - name: Checks Upstream
        run: npm run checkversion
