name: Publish to NPM
on:
  push:
    paths:
      - 'package.json'
    branches:
      - master
  workflow_dispatch:
jobs:
  Build-Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          always-auth: true

      - uses: pogfi/pnpm-install-cache@v0.0.3
        name: Install pnpm

      - name: Build package
        run: pnpm run build

      - name: SetupAuth
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Publish package on NPM 📦
        run: pnpm publish -r
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
