name: Publish to NPM
on:
  push:
    paths:
      - 'package.json'
    branches:
      - master
  workflow_dispatch:
jobs:
  Build-Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
        with:
          version: latest
          standalone: true
          run_install: true

      - name: Build package
        run: pnpm run build

      - name: SetupAuth
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Publish package on NPM 📦
        run: pnpm publish -r
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
